### PR TITLE
Exit upon compilation failure

### PR DESCRIPTION
**Pull request by charlie-haley**

### CODE REVIEW

**Comment by leaanthony** [comment]
Hey @charlie-haley! I'm not sure I ever saw the notification for this a year ago 😱 Is there anything that should be done?

**Comment by charlie-haley** [comment]
> Hey @charlie-haley! I'm not sure I ever saw the notification for this a year ago scream Is there anything that should be done?

No problem! It was quite a while ago when I had this issue, I believe it wasn't exiting properly when it reached a failure, happy to re-open if you think it's still valid

**Comment by charlie-haley** [comment]
Yeah that was the issue https://github.com/wailsapp/wails/issues/649#issuecomment-823177547, my CI builds were marked as successful even if they failed

**Comment by leaanthony** [comment]
Happy to merge it

**Comment by charlie-haley** [comment]
I realised I have no way to test this currently as I haven't had as much time to work on my project using Wails as I would like. So, I'll keep this PR closed for now and open it again if/when I encounter the issue again 😅

**Pull request closed without merging**
